name: 'Microsoft Teams Notifications Card'
description: 'Send a custom notification message to a Microsoft Teams channel with GitHub repo details'
branding:
  icon: message-circle
  color: purple 
inputs:
  github-token:
    description: 'GitHub Token'
    required: true 
  ms-teams-webhook-uri:
    description: 'Microsoft Teams Webhook URI'
    required: true 
  notification-summary:
    description: 'Message to be sent to Microsoft Teams channel'
    required: true 
  notification-color:
    description: 'Color of notification header line'
    required: true 
  timezone:
    description: 'Timezone (ex. Europe/Berlin)'
    required: false
  github-enterprise-host:
    description: 'Enterprise github host'
    required: false
    default: github.com
  card-type:
    description: 'support two types; true is adaptive card, false is message card'
    required: false
    type: boolean
    default: true
runs:
  using: 'node20'
  main: 'dist/index.js'
